Notebook for us to start working in.

# PPOL 5203 Final Project

## 1. Import Data and Clean Columns

In [8]:
#!pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.2-py2.py3-none-any.whl (249 kB)
     ---------------------------------------- 0.0/250.0 kB ? eta -:--:--
     - -------------------------------------- 10.2/250.0 kB ? eta -:--:--
     - -------------------------------------- 10.2/250.0 kB ? eta -:--:--
     ---- -------------------------------- 30.7/250.0 kB 325.1 kB/s eta 0:00:01
     ------------- ----------------------- 92.2/250.0 kB 744.7 kB/s eta 0:00:01
     -------------------------------------- 250.0/250.0 kB 1.5 MB/s eta 0:00:00
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-1.1.0-py3-none-any.whl (4.7 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-1.1.0 openpyxl-3.1.2

In [1]:
import pandas as pd
import os
import openpyxl

In [2]:
pwd

'C:\\Users\\bsullivan\\OneDrive - FI Consulting\\Documents\\GU\\Data Science 1\\PPOL5203_FinalProject\\Python_code'

In [3]:
os.chdir("../")
os.chdir('Datasets/Orig_Data')

In [4]:
# import County Health Data
County_Health_xl = pd.read_excel("2023_County_Health_Rankings_Data.xlsx", sheet_name = ['Additional Measure Data'],skiprows = 1, usecols = ['FIPS', 'State', 'County', 'Life Expectancy', 'Age-Adjusted Death Rate', '% Frequent Physical Distress', '% Frequent Mental Distress', 'Population','% Less than 18 Years of Age','% 65 and Over','% American Indian or Alaska Native','% Asian','% Native Hawaiian or Other Pacific Islander','% Hispanic','% Non-Hispanic White','% Not Proficient in English','% Female','% Rural'])

#'% Non-Hispanic Black' couldn't find this one to add as a column

In [ ]:
# subset the dictionary provided by the sheet needed and save as a new dataframe
County_Health_Addl_Measures = County_Health_xl['Additional Measure Data']

In [9]:
County_Health_Addl_Measures.head()

,FIPS,State,County,Life Expectancy,Age-Adjusted Death Rate,% Frequent Physical Distress,% Frequent Mental Distress,Population,% Less than 18 Years of Age,% 65 and Over,% American Indian or Alaska Native,% Asian,% Native Hawaiian or Other Pacific Islander,% Hispanic,% Non-Hispanic White,% Not Proficient in English,% Female,% Rural
0,1000,Alabama,NaN,74.835949,499.868550,11.077397,16.484296,5039877,22.267448,17.635688,0.714442,1.550435,0.108832,4.785196,64.877099,1.027596,51.425422,40.963183
1,1001,Alabama,Autauga,76.585650,427.073326,10.700000,16.200000,59095,23.406380,16.048735,0.458584,1.203147,0.118453,3.326847,72.454522,0.231241,51.378289,42.002162
2,1003,Alabama,Baldwin,77.724729,381.702031,9.900000,16.100000,239294,21.218250,21.469824,0.800271,1.122469,0.068535,4.841743,83.148763,0.759661,51.347715,42.279099
3,1005,Alabama,Barbour,72.867210,589.566095,14.900000,18.000000,24964,20.549591,19.976767,0.725044,0.460663,0.232335,4.959141,45.305240,1.382681,46.703253,67.789635
4,1007,Alabama,Bibb,73.609363,567.508146,12.700000,17.400000,22477,20.118343,16.737109,0.502736,0.275838,0.129021,3.087601,73.564088,0.443062,46.015927,68.352607

In [6]:
County_Health_xl_ranked_data = pd.read_excel("2023_County_Health_Rankings_Data.xlsx", sheet_name = ['Ranked Measure Data'],skiprows = 1, usecols =['FIPS','% Fair or Poor Health', 'Average Number of Physically Unhealthy Days', 'Average Number of Mentally Unhealthy Days', '# Primary Care Physicians','Primary Care Physicians Rate','Primary Care Physicians Ratio', '# Dentists', 'Dentist Rate','Dentist Ratio', 'Average Daily PM2.5', 'Presence of Water Violation', '# Mental Health Providers','Mental Health Provider Rate','Mental Health Provider Ratio'])

In [7]:
# subset the dictionary provided by the sheet needed and save as a new dataframe
County_Health_Ranked_Measures = County_Health_xl_ranked_data['Ranked Measure Data']

In [27]:
# clean column names
County_Health_Ranked_Measures.rename(columns=lambda x: x.replace(" ", "_").replace("%", "Percent").replace("#", "Number"), inplace=True)

# Do we want to convert percents to decimals?
# Do we want the ratios for dentist, primary care, mental health?

In [28]:
County_Health_Ranked_Measures.head()

,FIPS,Percent_Fair_or_Poor_Health,Average_Number_of_Physically_Unhealthy_Days,Average_Number_of_Mentally_Unhealthy_Days,Number_Primary_Care_Physicians,Primary_Care_Physicians_Rate,Primary_Care_Physicians_Ratio,Number_Dentists,Dentist_Rate,Dentist_Ratio,Number_Mental_Health_Providers,Mental_Health_Provider_Rate,Mental_Health_Provider_Ratio,Average_Daily_PM2.5,Presence_of_Water_Violation
0,1000,18.9,3.482416,5.073277,3238.0,65.79252,1520:1,2454.0,48.69166,2054:1,6321.0,125.41973,797:1,9.3,NaN
1,1001,16.9,3.432211,4.797351,25.0,44.52756,2246:1,19.0,32.15162,3110:1,21.0,35.53600,2814:1,10.0,No
2,1003,14.9,3.276177,4.753750,150.0,65.42019,1529:1,114.0,47.64014,2099:1,250.0,104.47399,957:1,7.6,Yes
3,1005,27.5,4.605432,4.954855,8.0,32.53487,3074:1,8.0,32.04615,3121:1,6.0,24.03461,4161:1,9.4,Yes
4,1007,21.6,4.012182,5.364779,14.0,63.24539,1581:1,6.0,26.69395,3746:1,9.0,40.04093,2497:1,9.8,No

,FIPS,Percent_Fair_or_Poor_Health,Average_Number_of_Physically_Unhealthy_Days,Average_Number_of_Mentally_Unhealthy_Days,#_Primary_Care_Physicians,Primary_Care_Physicians_Rate,Primary_Care_Physicians_Ratio,#_Dentists,Dentist_Rate,Dentist_Ratio,#_Mental_Health_Providers,Mental_Health_Provider_Rate,Mental_Health_Provider_Ratio,Average_Daily_PM2.5,Presence_of_Water_Violation
0,1000,18.9,3.482416,5.073277,3238.0,65.79252,1520:1,2454.0,48.69166,2054:1,6321.0,125.41973,797:1,9.3,NaN
1,1001,16.9,3.432211,4.797351,25.0,44.52756,2246:1,19.0,32.15162,3110:1,21.0,35.53600,2814:1,10.0,No
2,1003,14.9,3.276177,4.753750,150.0,65.42019,1529:1,114.0,47.64014,2099:1,250.0,104.47399,957:1,7.6,Yes
3,1005,27.5,4.605432,4.954855,8.0,32.53487,3074:1,8.0,32.04615,3121:1,6.0,24.03461,4161:1,9.4,Yes
4,1007,21.6,4.012182,5.364779,14.0,63.24539,1581:1,6.0,26.69395,3746:1,9.0,40.04093,2497:1,9.8,No

In [10]:
os.chdir('NRI_Table_Counties')

In [11]:
#import NRI data 
NRI_df = pd.read_csv("NRI_Table_Counties.csv", usecols = ['STATE', 'STATEABBRV', 'COUNTY','STCOFIPS', 'POPULATION','AREA','RISK_SCORE','RISK_RATNG','EAL_SCORE','EAL_RATNG','SOVI_SCORE','SOVI_RATNG','RESL_SCORE','RESL_RATNG'])

In [ ]:
NRI_df.head()

In [ ]:
os.chdir('../')

In [20]:
#import Places data 
Places_df = pd.read_csv("PLACES__Local_Data_for_Better_Health__County_Data_2023_release.csv", usecols = ['StateAbbr', 'StateDesc', 'LocationName', 'Geolocation'])

In [22]:
Places_df.head()

  StateAbbr StateDesc LocationName                     Geolocation
0        GA   Georgia         Ware   POINT (-82.4215072 31.050881)
1        IN   Indiana         Ohio   POINT (-84.9642994 38.940527)
2        IN   Indiana         Owen  POINT (-86.8388453 39.3173394)
3        IA      Iowa         Iowa  POINT (-92.0591226 41.6839184)
4        IA      Iowa       Marion  POINT (-93.0938678 41.3314327)

## 2. Merge Datasets together by FIPS